// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/helper/solarPanelDataExtractor.go

// Package mock_helper is a generated GoMock package.
package mock_helper

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/loukaspe/solar-panel-data-crud/internal/core/domain"
)

// MockSolarPanelDataEventExtractorInterface is a mock of SolarPanelDataEventExtractorInterface interface.
type MockSolarPanelDataEventExtractorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSolarPanelDataEventExtractorInterfaceMockRecorder
}

// MockSolarPanelDataEventExtractorInterfaceMockRecorder is the mock recorder for MockSolarPanelDataEventExtractorInterface.
type MockSolarPanelDataEventExtractorInterfaceMockRecorder struct {
	mock *MockSolarPanelDataEventExtractorInterface
}

// NewMockSolarPanelDataEventExtractorInterface creates a new mock instance.
func NewMockSolarPanelDataEventExtractorInterface(ctrl *gomock.Controller) *MockSolarPanelDataEventExtractorInterface {
	mock := &MockSolarPanelDataEventExtractorInterface{ctrl: ctrl}
	mock.recorder = &MockSolarPanelDataEventExtractorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolarPanelDataEventExtractorInterface) EXPECT() *MockSolarPanelDataEventExtractorInterfaceMockRecorder {
	return m.recorder
}

// ExtractEventsPerParameterIdToCsvForm mocks base method.
func (m *MockSolarPanelDataEventExtractorInterface) ExtractEventsPerParameterIdToCsvForm(arg0 *domain.SolarPanelData) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractEventsPerParameterIdToCsvForm", arg0)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractEventsPerParameterIdToCsvForm indicates an expected call of ExtractEventsPerParameterIdToCsvForm.
func (mr *MockSolarPanelDataEventExtractorInterfaceMockRecorder) ExtractEventsPerParameterIdToCsvForm(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractEventsPerParameterIdToCsvForm", reflect.TypeOf((*MockSolarPanelDataEventExtractorInterface)(nil).ExtractEventsPerParameterIdToCsvForm), arg0)
}
